channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=23.0.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.21.5
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - scipy==1.7.3
  - typing-extensions==4.5.0
name: mlflow-env
